include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: false
  # exclude:
  #   - lib/src/**.dart
  # enable-experiment:
  #   - extension-methods

#  https://dart-lang.github.io/linter/lints/